sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 5.6
  - 7.1

cache:
  - $HOME/.composer/cache

before_script:
  - ./bin/bootstrap

script: ./bin/test --no-ansi
